### ISSUE TITLE
the img

### ISSUE THREAD

**Issue by cloudflypeng** [DORAKIKA/iak#25]
<img width="749" alt="image" src="https://github.com/DORAKIKA/iak/assets/44285412/6199b22d-1318-4af1-aa01-043130888671">

the img in the readme is wrong

**Comment by DORAKIKA** [comment]
thanks！

fixed on [this commit](https://github.com/DORAKIKA/iak/commit/f8ebc72f03e316a7fe01b7d4fc209967c16f8a6f)
